from __future__ import annotations

import argparse
import sys
from pathlib import Path
from time import perf_counter

import numpy as np
from scipy.spatial.distance import pdist

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from config import DISTANCE, VECTORIZE_BATCH_SIZE, make_vectorizer

FASTA_SUFFIXES = {".fasta", ".fa", ".fna", ".fas"}


def read_single_fasta(path: Path) -> tuple[str, str]:
    sequence_parts: list[str] = []
    header_count = 0

    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            if line.startswith(">"):
                header_count += 1
                if header_count > 1:
                    raise ValueError(f"{path} contains more than one FASTA record")
                continue
            if header_count == 0:
                raise ValueError(f"{path} contains sequence data before its FASTA header")
            sequence_parts.append(line)

    if header_count == 0:
        raise ValueError(f"{path} does not contain a FASTA header")

    sequence = "".join(sequence_parts).lower()
    if not sequence:
        raise ValueError(f"{path} contains an empty sequence")

    # AFproject's CRM dataset stores one sequence per file and uses these
    # filename identifiers in its published dataset structure.
    return path.stem, sequence


def load_dataset(dataset_dir: Path) -> tuple[list[str], list[str]]:
    files = sorted(
        path
        for path in dataset_dir.rglob("*")
        if path.is_file() and path.suffix.lower() in FASTA_SUFFIXES
    )
    if not files:
        raise FileNotFoundError(f"No FASTA files found under {dataset_dir}")

    ids: list[str] = []
    sequences: list[str] = []
    for path in files:
        seq_id, sequence = read_single_fasta(path)
        ids.append(seq_id)
        sequences.append(sequence)

    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate filename-based sequence identifiers were found")
    return ids, sequences


def detect_alphabet(sequences: list[str]) -> str:
    chars = "".join(sorted({ch for sequence in sequences for ch in sequence}))
    if not chars:
        raise ValueError("Dataset alphabet is empty")
    return chars


def vectorize_batched(sequences: list[str], chars: str, batch_size: int) -> np.ndarray:
    encoder = make_vectorizer(chars)
    parts: list[np.ndarray] = []
    total = len(sequences)
    t0 = perf_counter()

    for start in range(0, total, batch_size):
        end = min(start + batch_size, total)
        parts.append(encoder.transform(sequences[start:end]))
        print(
            f"\rVectorizing {end:,}/{total:,} ({100.0 * end / total:5.1f}%) "
            f"{perf_counter() - t0:7.1f}s",
            end="",
            flush=True,
        )
    print()
    return np.vstack(parts)


def write_afproject_tsv(ids: list[str], vectors: np.ndarray, output: Path) -> None:
    # scipy.spatial.distance.pdist returns distances in the same upper-triangle
    # pair order generated by the nested loops below.
    distances = pdist(vectors.astype(np.float64, copy=False), metric=DISTANCE)
    if not np.all(np.isfinite(distances)):
        raise RuntimeError("Non-finite pairwise distances were produced")

    output.parent.mkdir(parents=True, exist_ok=True)
    cursor = 0
    with output.open("w", encoding="utf-8", newline="") as handle:
        for i in range(len(ids) - 1):
            for j in range(i + 1, len(ids)):
                handle.write(f"{ids[i]}\t{ids[j]}\t{distances[cursor]:.12g}\n")
                cursor += 1

    expected = len(ids) * (len(ids) - 1) // 2
    if cursor != expected:
        raise RuntimeError(f"Expected {expected} distances, wrote {cursor}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a direct AFproject CRM submission using the single config.py setup."
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=ROOT / "datasets" / "crm",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "results" / "crm_distances.tsv",
    )
    args = parser.parse_args()

    ids, sequences = load_dataset(args.data_dir)
    print(f"Loaded {len(sequences):,} CRM sequences")
    chars = detect_alphabet(sequences)
    print(f"Detected alphabet: {chars} ({len(chars)} symbols)")
    vectors = vectorize_batched(sequences, chars, VECTORIZE_BATCH_SIZE)
    print(f"Vector dimension: {vectors.shape[1]}")
    print(f"Distance: {DISTANCE}")

    write_afproject_tsv(ids, vectors, args.output)
    print(f"AFproject-ready TSV: {args.output}")
    print("Upload this file directly to the AFproject CRM benchmark page.")


if __name__ == "__main__":
    main()
